### ISSUE TITLE
App crashing at time of initialize

### ISSUE THREAD

**Issue by pritamparker** [hybriteq/react-native-floating-bubble#1]
` initialize().then(() => console.log('Initialized the bubble mange'));`

app getting crash.

It's happening in Android Oreo.

**Comment by janakact** [comment]
Did you get the permission.? 

Request permission first and then initialize.

**Comment by pritamparker** [comment]
I requested permission. it prints request granted. after that it getting crashed.

**Comment by jdevelopervimal** [comment]
Same prob here..

**Comment by SilvioLuis** [comment]
Same here! 
```
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@93395e2 -- permissi
                            on denied for window type 2006
```

**Comment by SilvioLuis** [comment]
I created a pull request with the solution (https://github.com/txusballesteros/bubbles-for-android/pull/49) ... apparently it's a problem with the dependency (https://github.com/txusballesteros/bubbles-for-android/issues/48)

**Comment by cparello** [comment]
Anybody going to fix this?


Its fixed in the dependency  https://github.com/txusballesteros/bubbles-for-android/issues?utf8=%E2%9C%93&q=2006

**Comment by ItaloEC** [comment]
this error occours in android 9 too.. any solution?

**Comment by sostenesg7** [comment]
this fix for me, #2 

 just open: node_modules/react-native-floating-bubble/android/build.gradle
    replace  compile 'com.txusballesteros:bubbles:1.2.1'
    to
    implementation 'com.github.txusballesteros:bubbles-for-android:develop-SNAPSHOT'

**Comment by janakact** [comment]
@sostenesg7  Deployed it as v1.0.7. Could you please check whether it's working, since I can't check it because I don't have react-native environment right now. 
Thanks in advance.

**Comment by ItaloEC** [comment]
you saved my life @sostenesg7

**Comment by janakact** [comment]
@ItaloEC does v1.0.7 work?

**Comment by sostenesg7** [comment]
> @ItaloEC does v1.0.7 work?

Yes @janakact, works perfectly. Thanks

**Comment by sostenesg7** [comment]
> @sostenesg7 Deployed it as v1.0.7. Could you please check whether it's working, since I can't check it because I don't have react-native environment right now.
> Thanks in advance.

Yes @janakact, works perfectly. Thanks

**Comment by janakact** [comment]
Thank you @sostenesg7

**Comment by dansalomon2015** [comment]
Thx a lot @sostenesg7. It works !!!

**Comment by Tarsem-tech** [comment]
@sostenesg7  But When i try to replace it and build again then it's give me error at build time 

just open: node_modules/react-native-floating-bubble/android/build.gradle
replace compile 'com.txusballesteros:bubbles:1.2.1'
to
implementation 'com.github.txusballesteros:bubbles-for-android:develop-SNAPSHOT'
