### ISSUE TITLE
Complete screen overlay with some information from app.#Paid_Task

### ISSUE THREAD

**Issue by 92sajid110** [hybriteq/react-native-floating-bubble#17]
i want to open some app from my app with some data and in that whole screen transparent overlay with some information and after some time ring back to app.
can it be done with this or somone help i will pay for this.
Thanks

**Comment by janakact** [comment]
You better develop some native code and use the 'draw over other apps' feature. I don't think it is possible to do it with this library.
So I am closing the issue.
