### ISSUE TITLE
How to change Icon of bubble by click event on bubble

### ISSUE THREAD

**Issue by princevatsal** [hybriteq/react-native-floating-bubble#5]
I want that when user click on floating bubble, then icon of bubble should change so that i can show some info on button like play icon , pause icon ,stop icon . Please help

**Comment by tuanphamanh91** [comment]
Hi @princevatsal, did you find the way to do that? Can you share here? Thank you!

**Comment by janakact** [comment]
Hi, I think you will have to modify the underlying android library to do that. 
Maybe for a music player, this will be helpful: https://github.com/cinder92/react-native-audio-floating-widget#readme

**Comment by princevatsal** [comment]
Thank you very much @janakact  for replying .

**Comment by princevatsal** [comment]
> Hi @princevatsal, did you find the way to do that? Can you share here? Thank you!

@tuanphamanh91  you have to make changes in Main Java file of module 
there you have to get the bubble icon  and then change the src of image of bubble

//write this in a function that is called by js in  RNFloatingBubble.java file
// give android:id="@+id/avatar" to ImageView in bubble_layout.xml 
ImageView imageView=(ImageView) view.findViewById(R.id.avatar); 
//place a file in res/drawable folder 
imageView.setImageResource(R.drawable.play);
